### PR TITLE
port color-eyre to new eyre with global hook

### PR DESCRIPTION
**Pull request by yaahc**
blocked on:

- [x] fix backtrace capture logic (disable panic capture while enabling error capture)
- [x] fix verbosity logic, when RUST_LIB_BACKTRACE=full it shows source lines on the panic backtraces but not on the error backtraces
- [x] https://github.com/yaahc/color-spantrace/issues/4
- [x] https://github.com/yaahc/color-spantrace/issues/5
- [x] https://github.com/yaahc/color-eyre/issues/31
- [x] make new release of color-spantrace and increment version to match in toml
- [x] update documentation
- [x] make new release of eyre and depend on it via crates.io
- [x] increment version numbers to prep for new release of color-eyre
- [x] ~~make it so `HookBuilder::default` and `HookBuilder::new` are different~~ add `HookBuilder::blank`

### CODE REVIEW

**Comment by SecurityInsanity** [comment]
Hey! Just started looking at the new release (not sure if this pr is the best discussion place, but this seemed to be the most ideal?).

Upon changing from: `^v0.4.3` to: `color-eyre = { git = "https://github.com/yaahc/color-eyre.git", branch = "hooked" }` (and changing my includes from `use color_eyre::section::help::Help;` to `use color_eyre::Help;`).

It seems the display is no longer working correctly?

Previously an error message that looked like:

ErrorNormalNoSpanTrace

(or the following with spantraces: 
ErrorWithSpantrace )

Now just prints out the message, regardless of spantrace status (or backtrace status!!!):

ErrorParseAsYaml

The full sourcecode is at: https://github.com/SecurityInsanity/dev-loop/tree/dev/errors  , However the general idea for this is:

```
let tlc_res = config::get_top_level_config();
if let Err(tlc_err) = tlc_res {
  warn!(
    "{:?}\n",
    tlc_err.wrap_err(
      "Invalid YAML Configuration, you will need a valid one if you want to run dev-loop"
    )
  );
}
```

Where `get_top_level_config()` returns a normal `Result<T, Error>` type.

**Comment by SecurityInsanity** [comment]
Ah! I had missed the addition of: `color_eyre::install()?;` It seems to be working as expected now.

However it looks #34 doesn't "just work" as it responds with a different error: 

```txt
no method named `note` found for struct `eyre::Report` in the current scope
method not found in `eyre::Report`
```

But other than that looks like messages are working the same.

**Comment by yaahc** [comment]
It looks like you probably just need to wrap it in an `Err()`, the extension trait that defines the `note` function is still only implemented for `Result<T, Report>`.

**Comment by yaahc** [comment]
@SecurityInsanity in the next release I'm planning on changing how we configure the default so its a method on the Builder for the hook installer that you can conditionally call

```rust
use color_eyre::config::HookBuilder;

HookBuilder::new()
    .capture_span_trace_by_default(false)
    .install()
    .unwrap();
```

Instead of the stuff you currently have to do with manually setting env variables if they were not set by the user. The old version should still work though so there's no risk of breaking things when you eventually upgrade.

**Comment by SecurityInsanity** [comment]
@yaahc definitely like that more. than mucking with environment variables. Not to mention it also simplifies my code which now is doing a branch on whether or not to print it and the like:

```rust
if add_spantrace {
    tracing_subscriber::registry()
        .with(filter_layer)
        .with(fmt_layer)
        .with(tracing_layer)
        .with(ErrorLayer::default())
        .init();
} else {
    tracing_subscriber::registry()
        .with(filter_layer)
        .with(fmt_layer)
        .with(tracing_layer)
        .init();
}
```

So I like the idea of just being able to pass in a boolean.

**Comment by yaahc** [comment]
Cool, it should all be in the `hooked` branch now, I'm just about done with polish for `color-eyre` so now all I have left to do is double check all the docs for `eyre` itself and then cut releases in all of the relevant crates.

**Comment by SecurityInsanity** [comment]
Yep, was just testing it out. It looks like that new hookbuilder flag works great! :heart:  I did one sweep more through my error messages, and everything seems to be working well. Thanks for your work on this!

**Pull request merged**
